server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

management:
  endpoints:
    web:
      exposure:
        # refresh: 설정정보 갱신, health: 앱 어플 상태 확인, httptrace: 호출 경로 확인
        include: refresh, health, beans, httptrace

spring:
  application:
    name: apigateway-service
  cloud:
    # 비동기 방식으로 서비스가 동작하기 때문에 Netty 로 서비스가 구동이 됨
    gateway:
      routes:
        # =========================== user-service LOGIN ===========================
        # user-service POST (로그인)
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/login
            - Method=POST
          # uri 에서 서비스 부분 필터링하는 필터
          filters:
            # POST로 들어오는 요청은 새로운 요청으로 처리할 수 있도록 Cookie 삭제
            - RemoveRequestHeader=Cookie
            # 사용자의 요청을 변경하는 처리
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        # =========================== user-service POST ===========================
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        # =========================== user-service GET ===========================
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/health-check
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        # =========================== user-service GET ===========================
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - CustomAuthorizationHeaderFilter
        # =========================== user-service ACTUATOR ===========================
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
